### ISSUE TITLE
Is it possible to do expansion for "."

### ISSUE THREAD

**Issue by maronin** [jrosdahl/fancy-dabbrev#1]
Lets say I have:

```
foo.hello
foo.bye

foo.
```

When I have the cursor after the ".", and I do try to do fancy-dabbrev-expand it doesn't work

I get:

`syntax: ((statement 42211)), indent: 28`

Why is that?

**Comment by maronin** [comment]
I ended up modifying `fancy-dabbrev--looking-back-at-expandable` function and removing ` (thing-at-point 'symbol)` so fancy-dabbrev can check periods as well!

**Comment by jrosdahl** [comment]
@maronin: Inspired by your question/solution I added a `fancy-dabbrev-expansion-context` setting in 
158e1e5.

**Comment by maronin** [comment]
Awesome! You are so quick!

Just a small nitpick. When expansion context is after-non-space, and expand is called after the "." the popup displays:

![image](https://user-images.githubusercontent.com/1514285/73393996-b9f5f900-42aa-11ea-8e23-a5920341c6ca.png)

So you see "foo." in the popup.

When you do foo.g and expand its fine:

![image](https://user-images.githubusercontent.com/1514285/73394104-f1fd3c00-42aa-11ea-8314-4fae6b59caee.png)

It's not a big deal, just aesthetics. I have no clue where to even look. Probably in the popup methods... Might just be the way dabbrevs works with completions 

Anyways, I love this package! Keep up the great work!

**Comment by jrosdahl** [comment]
Right, I think I'll leave it as is since the `foo.` prefix in the first case is part of the string that dabbrev-expand searches for so keeping it likely makes it more clear what happens.
