### ISSUE TITLE
Feature request support for vterm

### ISSUE THREAD

**Issue by ram535** [jrosdahl/fancy-dabbrev#12]
Is it possible to add vterm support for commands completion and also completion for files and directories in the cwd. 
There is an incomplete solution in the [vterm repo](https://github.com/akermu/emacs-libvterm/pull/401).

**Comment by jrosdahl** [comment]
I'm not familiar with vterm, but it doesn't sound like it would be in scope of fancy-dabbrev which is not planned to be more intelligent than just wrapping plain `dabbrev-expand`. Similarly, completing files and directories is also out of scope. Sorry!

**Comment by ram535** [comment]
You are right, thanks anyway.
