### ISSUE TITLE
dabbrev--substitute-expansion: Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by claha** [jrosdahl/fancy-dabbrev#17]
Tried out the package after your latest updates, works find with a clean configuration but after applying some configuration of dabbrev I get the error stated in the title. The error appears when I execute `fancy-dabbrev-expand` the second time, first time there are no problems.

I just discovered this and haven't had time to dig into what part of the configuration is causing this but it is one of these lines. 
```
(use-package dabbrev
  :straight (:type built-in)
  :custom
  (dabbrev-case-replace nil)
  (dabbrev-backward-only nil)
  (dabbrev-case-distinction nil)
  (dabbrev-case-fold-search t)
  (dabbrev-check-all-buffers t)
  (dabbrev-abbrev-char-regexp nil)
  (dabbrev-eliminate-newlines nil)
  (dabbrev-check-other-buffers t)
  (dabbrev-upcase-means-case-search t))
```
I will try to have a look at this myself but perhaps you can spot the bug in your code or if I have some invalid configuration.

Thansk for a great package!

**Comment by jrosdahl** [comment]
Right, I see the problem. Will fix.
