### ISSUE TITLE
Request/Suggestion: support for limiting completion to when the preview is visible

### ISSUE THREAD

**Issue by ideasman42** [jrosdahl/fancy-dabbrev#2]
Hi, this is an incredibly handy package, I've managed to tweak it's behavior using advice but thought it would be worth posting an issue, since the functionality could be supported more cleanly in the package.

My preferred default behavior when pressing the complete key is as follows:

- When there is a preview, complete.
- When there isn't, perform `indent-for-tab-command`.

Currently I sometimes press the key for `fancy-dabbrev-expand-or-indent` and even when no completion is possible, it's showing an error instead of calling `indent-for-tab-command`.

I've managed to workaround this ([see link](
https://www.reddit.com/r/emacs/comments/oksdhh/package_praise_prodigy_and_fancydabbrev/h5c9tad?utm_source=share&utm_medium=web2x&context=3))

---

This could be solved in a few ways, some suggestions:

- Add `(fancy-dabbrev-is-showing-preview)` so anyone who wants to check this can do so easily & customize the exact behavior.
- Add a custom setting so complete is only attempted when the preview is visible.

Note that I'm happy to submit a PR for any of these.

**Comment by jrosdahl** [comment]
Thanks for the kind words! Nice to hear that somebody else finds my small hack useful. :slightly_smiling_face:
