### ISSUE TITLE
Message suppression isn't working for `*Messages*`

### ISSUE THREAD

**Issue by ideasman42** [jrosdahl/fancy-dabbrev#9]
When typing with `fancy-dabbrev` mode my message buffer is flooded with `Scanning for dabbrevs...done`:

(tested with emacs28 from master).

```
Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done

Scanning for dabbrevs...done
```

----

Temporary disabling `make-progress-reporter`, `progress-reporter-update` & `progress-reporter-done` should resolve the issue.

Advising these functions with a disabled `message` function could also work.

I use this macro for tasks like this:

    (defmacro fancy-dabbrev--with-advice (fn-orig where fn-advice &rest body)
      "Execute BODY with advice added WHERE using FN-ADVICE temporarily added to FN-ORIG."
      `
      (let ((fn-advice-var ,fn-advice))
        (unwind-protect
          (progn
            (advice-add ,fn-orig ,where fn-advice-var)
            ,@body)
          (advice-remove ,fn-orig fn-advice-var))))

**Comment by jrosdahl** [comment]
I don't remember the details, but I think that I only cared about suppressing messages from the mode line, not from the `*Messages*` buffer, so for me it works like intended (at least in Emacs 27).

That said, improvements are welcome. :slightly_smiling_face:

**Comment by ideasman42** [comment]
I see a flicker in the echo area too, although very briefly.

**Comment by ideasman42** [comment]
Submitted fix, it's more verbose than I'd like, but it's working without suppressing all messages (which could suppress warnings/info), just suppress the progress report.
